import Head from "next/head";
import styles from "../styles/Home.module.css";
import Header from "../components/Header";
import Navbar from "../components/Navbar";
import Results from "../components/Results";
import requests from "../utils/requests";

export default function Home({ results }) {
  console.log("Index Called");
  return (
    <div className={styles.container}>
      <Head>
        <title>NETFLIX</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/NETFLIXico.jpg" />
      </Head>
      <Header />
      <Navbar />

      <Results results={results} />
    </div>
  );
}

export async function getServerSideProps(context) {
  const genre = context.query.genre;
  console.log("genre is ", genre);

  const request = await fetch(
    `https://api.themoviedb.org/3${
      requests[genre]?.url || requests.fetchTrending.url
    }`
  );

  const data = await request.json();
  console.log("data fecthed ");
  return {
    props: {
      results: data.results,
    },
  };
}
